// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt8vhDuGP_tIQQipMo-SM93Rb-9mlXXxw',
    appId: '1:313656543199:web:b4dcbc3e746055b45ba66a',
    messagingSenderId: '313656543199',
    projectId: 'project1-da437',
    authDomain: 'project1-da437.firebaseapp.com',
    storageBucket: 'project1-da437.appspot.com',
    measurementId: 'G-NQWC24VHF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVBw5OkZQ-QyB4H_41ApVAfL3uZRAkiSM',
    appId: '1:313656543199:android:abc0ac5c6150ab835ba66a',
    messagingSenderId: '313656543199',
    projectId: 'project1-da437',
    storageBucket: 'project1-da437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhl0RglD7Y33MoPzivLw7rvebX_Sj6onE',
    appId: '1:313656543199:ios:0a91d498a998da455ba66a',
    messagingSenderId: '313656543199',
    projectId: 'project1-da437',
    storageBucket: 'project1-da437.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhl0RglD7Y33MoPzivLw7rvebX_Sj6onE',
    appId: '1:313656543199:ios:0a91d498a998da455ba66a',
    messagingSenderId: '313656543199',
    projectId: 'project1-da437',
    storageBucket: 'project1-da437.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt8vhDuGP_tIQQipMo-SM93Rb-9mlXXxw',
    appId: '1:313656543199:web:03d2118aa91c873b5ba66a',
    messagingSenderId: '313656543199',
    projectId: 'project1-da437',
    authDomain: 'project1-da437.firebaseapp.com',
    storageBucket: 'project1-da437.appspot.com',
    measurementId: 'G-9K9L6QQHQN',
  );
}
